apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kleinanzeigen-monitor-seen
  namespace: kleinanzeigen-monitor
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 64Mi
  storageClassName: local-path
